name: currency_rates
description: A sample Flutter application illustrating Freezed package usage
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  http: ^0.13.4
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  lint: ^1.8.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/
