name: currency_rates
description: A sample Flutter application illustrating sealed classes usage.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  equatable: ^1.2.4
  flutter_bloc: ^6.0.2
  get_it: ^4.0.4
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
