name: currency_rates
description: A sample Flutter application illustrating sealed classes usage.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.5
  flutter_bloc: ^6.0.6
  get_it: ^5.0.1
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
