name: currency_rates
description: A sample Flutter application illustrating Sealed Unions usage.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  http: ^0.13.4
  meta: ^1.7.0
  sealed_flutter_bloc: ^8.0.0
  sealed_unions: ^3.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/
